### ISSUE TITLE
Robotron link not valid

### ISSUE THREAD

**Issue by jpmondet** [abakuz/neteng-roadmap#1]
Hello !

First thanks for the roadmap, this is very cool ;-) 

It looks like the link https://shorturl.at/hjvT1 written in the "Source of Truth/Inventory/Modeling" module is not valid anymore.

I guess it is meant to point to https://research.fb.com/wp-content/uploads/2016/11/robotron_top-down_network_management_at_facebook_scale.pdf ? 

Thanks again !

**Comment by eovchar** [comment]
@jpmondet Hi! Thanks for the feedback and for pointing out the broken links, they have been fixed now.

And yes, you have the correct link to FB Robotron
